# Generated by Django 4.2.4 on 2023-08-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(default=None, max_length=150, null=True, verbose_name='custom name')),
                ('name_e', models.CharField(max_length=30, verbose_name='english name')),
                ('name_g', models.CharField(max_length=30, verbose_name='georgian name')),
                ('name_r', models.CharField(max_length=30, verbose_name='russian name')),
                ('custom_order', models.IntegerField(default=None, null=True, verbose_name='custom order')),
                ('color', models.IntegerField(default=None, null=True, verbose_name='color')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create date')),
            ],
            options={
                'verbose_name_plural': 'Diction',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='InsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(default=None, max_length=150, null=True, verbose_name='custom name')),
                ('name_e', models.CharField(max_length=150, verbose_name='english name')),
                ('name_g', models.CharField(max_length=150, verbose_name='georgian name')),
                ('name_r', models.CharField(max_length=150, verbose_name='russian name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('diction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.diction', verbose_name='diction id')),
            ],
            options={
                'verbose_name_plural': 'InsTypes',
                'ordering': ('id',),
            },
        ),
    ]
