# Generated by Django 4.2.4 on 2023-10-09 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_num', models.IntegerField(default=None, null=True, verbose_name='extra number')),
                ('name_e', models.CharField(max_length=30, verbose_name='english name')),
                ('name_g', models.CharField(max_length=30, verbose_name='georgian name')),
                ('name_r', models.CharField(max_length=30, verbose_name='russian name')),
                ('sname_e', models.CharField(max_length=30, verbose_name='english name')),
                ('sname_g', models.CharField(max_length=30, verbose_name='georgian name')),
                ('sname_r', models.CharField(max_length=30, verbose_name='russian name')),
                ('cust_type', models.IntegerField(default=0, verbose_name='all types of customers')),
                ('parent_cust', models.IntegerField(default=None, null=True, verbose_name='parent customer')),
                ('org_type', models.IntegerField(default=None, null=True)),
                ('sex', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('close_date', models.DateTimeField(default=None, null=True)),
                ('vip_state', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Cust_Name_His',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_e', models.CharField(max_length=30)),
                ('name_g', models.CharField(max_length=30)),
                ('name_r', models.CharField(max_length=30)),
                ('sname_e', models.CharField(max_length=30)),
                ('sname_g', models.CharField(max_length=30)),
                ('sname_r', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user who add row')),
            ],
            options={
                'db_table': 'customers_his',
            },
        ),
    ]
